option(ENABLE_ASAN "Enable AddressSanitizer in Debug" ON)
option(ENABLE_UBSAN "Enable UndefinedBehaviorSanitizer in Debug" ON)

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
  if(ENABLE_ASAN)
    add_compile_options(-fsanitize=address -fno-omit-frame-pointer)
    add_link_options(-fsanitize=address)
  endif()
  if(ENABLE_UBSAN)
    add_compile_options(-fsanitize=undefined)
    add_link_options(-fsanitize=undefined)
  endif()
endif()
